image: docker:git
services:
  - docker:dind

before_script:
  - docker info

build_image:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/
    - docker build -t registry.gitlab.com/kathra/kathra/kathra-services/kathra-appmanager/kathra-appmanager-java/kathra-appmanager-swagger:latest .
    - docker push registry.gitlab.com/kathra/kathra/kathra-services/kathra-appmanager/kathra-appmanager-java/kathra-appmanager-swagger:latest